In [1]:
import pandas as pd
import numpy as np
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import matplotlib.pyplot as plt
from datetime import datetime as dt

In [2]:
df = pd.read_csv('CitiBike_with_weather.csv', index_col=0)

C:\Users\anika\AppData\Local\Temp\ipykernel_11896\3420840328.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('CitiBike_with_weather.csv', index_col=0)

In [21]:
#Creating a sample 
df_sample = df.sample(frac=0.0042, random_state=32)

In [22]:
df_sample.to_csv(r'C:\Users\anika\New_York_CitiBike/sample_data.csv', index=False)

In [23]:
df_sample.head()

,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,date,avgWeather,_merge
ride_id,,,,,,,,,,,,,,,
7C0F145DA1196A83,classic_bike,2022-06-28 20:22:42.856,2022-06-28 20:58:45.315,Lexington Ave & E 29 St,6164.09,West St & Chambers St,5329.03,40.743116,-73.982154,40.717548,-74.013221,member,2022-06-28,22.4,both
4C6E227AFD04F78D,classic_bike,2022-06-06 13:50:07.675,2022-06-06 14:00:52.526,Eastern Pkwy & Washington Ave,3928.08,St Marks Pl & 4 Ave,4249.10,40.671649,-73.963115,40.681778,-73.979890,member,2022-06-06,22.2,both
1CCB4BDDA45EFA2E,classic_bike,2022-09-10 11:58:10.528,2022-09-10 11:59:59.516,Vernon Blvd & 10 St,6937.07,Broadway & 12 St,6901.01,40.767186,-73.937355,40.766800,-73.934777,member,2022-09-10,23.6,both
AC813D49B94F4918,classic_bike,2022-10-19 18:21:29.330,2022-10-19 18:24:42.673,W 21 St & 6 Ave,6140.05,W 20 St & 8 Ave,6224.05,40.741740,-73.994156,40.743453,-74.000040,member,2022-10-19,10.0,both
C27ADA453A0D6C98,classic_bike,2022-10-19 09:04:40.554,2022-10-19 09:11:12.149,E 11 St & 1 Ave,5746.14,E 16 St & 5 Ave,6022.04,40.729538,-73.984267,40.737262,-73.992390,member,2022-10-19,10.0,both

In [2]:
df = pd.read_csv('sample_data.csv', index_col=0)

In [3]:
#columns for month and season
df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d')
df['month'] = df['date'].dt.month
df['month'] = df['month'].astype('int')
df['season'] = [
    "winter" if (month == 12 or 1 <= month <= 4)
    else "spring" if (4 < month <= 5)
    else "summer" if (6 < month <= 9)
    else "fall"
    for month in df['month']]

In [4]:
# Create 'bike_rides_daily' by aggregating trips by date
if 'bike_rides_daily' not in df.columns:
    df['value'] = 1  # Temporary column for counting trips
    df_bike_rides = df.groupby('date', as_index=False).agg({'value': 'sum'})
    df_bike_rides = df_bike_rides.rename(columns={'value': 'bike_rides_daily'})
    df = df.merge(df_bike_rides, on='date', how='left')
    df = df.drop(columns=['value'])

In [6]:
df.to_csv(r'C:\Users\anika\New_York_CitiBike/sample_data_V2.csv', index=False)